export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const PRODUCTS_BY_BRAND = 'PRODUCTS_BY_BRAND';
export const PRODUCTS_BY_CATEGORY = 'PRODUCTS_BY_CATEGORY';
export const GET_PRODUCT_SEARCH = 'GET_PRODUCT_SEARCH';
export const GET_PRODUCTS_FILTERED = 'GET_PRODUCTS_FILTERED';
